<guests>
<guestid>2318</guestid>
<guestfirst>Ben</guestfirst>
<guestlast>Sala</guestlast>
<bookings><CheckinDate>2008-04-28</CheckinDate>
<Nights>4</Nights>
</bookings>
</guests>
<guests>
<guestid>2331</guestid>
<guestfirst>Chris</guestfirst>
<guestlast>Walls</guestlast>
<bookings><CheckinDate>2008-05-02</CheckinDate>
<Nights>2</Nights>
</bookings>
</guests>
<guests>
<guestid>2263</guestid>
<guestfirst>Tim</guestfirst>
<guestlast>Daley</guestlast>
<bookings><CheckinDate>2008-04-15</CheckinDate>
<Nights>2</Nights>
</bookings>
</guests>
<guests>
<guestid>2280</guestid>
<guestfirst>Danny</guestfirst>
<guestlast>Massimini</guestlast>
<bookings><CheckinDate>2008-05-11</CheckinDate>
<Nights>3</Nights>
</bookings>
</guests>