main : lab1part1.cpp lab1part2.cpp lab1part3.cpp lab1part4.cpp
	g++ -IGL -IGLU -lglut lab1part1.cpp -o lab1part1
	g++ -IGL -IGLU -lglut lab1part2.cpp -o lab1part2
	g++ -IGL -IGLU -lglut lab1part3.cpp -o lab1part3
	g++ -IGL -IGLU -lglut lab1part4.cpp -o lab1part4

clean : 
	rm -rf lab1part1
	rm -rf lab1part2
	rm -rf lab1part3
	rm -rf lab1part4
